#ifndef TILITAPAHTUMATLIB_GLOBAL_H
#define TILITAPAHTUMATLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TILITAPAHTUMATLIB_LIBRARY)
#define TILITAPAHTUMATLIB_EXPORT Q_DECL_EXPORT
#else
#define TILITAPAHTUMATLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // TILITAPAHTUMATLIB_GLOBAL_H
